### ISSUE TITLE
Rest apinya pindah bang?

### ISSUE THREAD

**Issue by RC047** [salismazaya/salism3api#2]
Bang gw butuh game mathnya bang,, link apinya masih ada gak? atau minta source buat dapetin soalnya aja bang pliss

**Comment by salismazaya** [comment]
saya kira gk ada yang pake terus api nya mati. sekarang dah hidup lagi api nya

**Comment by RC047** [comment]
> saya kira gk ada yang pake terus api nya mati. sekarang dah hidup lagi api nya

Masih ada bang banyak,, soalnya ini saya dapet link apimu dari repository public
